[project]
name = "monitoring"
version = "0.1.0"
description = "Monitoring framework to test UAS Service Suppliers"
readme = "README.md"
requires-python = "==3.12.6"
dependencies = [
    "aiohttp",
    "arrow",
    "bc-jsonpath-ng",
    "cryptography",
    "faker",
    "flask",
    "flask-login",
    "geojson",
    "gevent",
    "google-auth",
    "graphviz",
    "gunicorn",
    "implicitdict",
    "jsonnet",
    "jsonschema",
    "jwcrypto",
    "kubernetes",
    "locust",
    "loguru",
    "lxml",
    "marko",
    "numpy",
    "oauthlib",
    "pem",
    "pip-tools",
    "psycopg[binary]",
    "pvlib",
    "pyjwt",
    "pykml",
    "pyopenssl",
    "pyproj",
    "pytest",
    "pytest-mock",
    "pyyaml",
    "requests",
    "s2sphere",
    "scipy",
    "shapely",
    "structlog",
    "termcolor",
    "testcontainers",
    "uas-standards",
    "uuid6",
]
