apiVersion: v1
kind: Secret
metadata:
  name: uss-qualifier-slack-secret
  namespace: DEV
  labels:
    app: uss-qualifier
type: Opaque
stringData:
  webhook-url: "https://hooks.slack.com/services/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"
  bot-token: "xoxb-4835892069510-9152059209265-MA5y5I6wNplYbY4cLF8SO7Bf"
  channel-id: "C094R1ZCH9N"
