name: Developers environment checks
permissions:
  contents: read
on:
  pull_request: # All
  push:
    branches:
      - main
jobs:
  windows:
    name: Clone on Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5
      - name: Checkout on Windows
        run: echo "Project successfully cloned on ${{ runner.os }}. See `Set up Job` stage for more details about the Runner."
  macos:
    name: Clone on Mac
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5
      - name: Checkout on Mac
        run: echo "Project successfully cloned on ${{ runner.os }}. See `Set up Job` stage for more details about the Runner."
